from __future__ import print_function, division, absolute_import

# -*- coding: utf-8 -*-
"""init.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OthZmi_IUSNUhCxdeku18rdtkU4TEAiZ
"""

import torch
import torchvision.models as models

resnet152 = models.resnet152(pretrained = True)
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
resnet152 = resnet152.to(device)

# Testing Inference
batch_size = 64 # 256 # use smaller value if you get OOM error
a = torch.rand(batch_size,3,224,224).to(device)
with torch.no_grad():
  b = resnet152(a)

print('Done!')