# -*- coding: utf-8 -*-
"""init.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OthZmi_IUSNUhCxdeku18rdtkU4TEAiZ
"""

import torch
import torchvision.models as models

resnet152 = models.resnet152(pretrained = True)
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
resnet152 = resnet152.to(device)

# Testing Inference
a = torch.rand(256,3,224,224).to(device)
with torch.no_grad():
  resnet152(a)